/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ImageAnalysisResult = IDL.Record({
  'verdict' : IDL.Text,
  'authenticityScore' : IDL.Nat,
  'manipulationIndicators' : IDL.Vec(IDL.Text),
  'deepfakeScore' : IDL.Nat,
  'confidence' : IDL.Nat,
});
export const AnalysisClassification = IDL.Variant({
  'misleading' : IDL.Null,
  'satire' : IDL.Null,
  'fake' : IDL.Null,
  'genuine' : IDL.Null,
});
export const AnalysisResult = IDL.Record({
  'biasIndicator' : IDL.Text,
  'keyPhrases' : IDL.Vec(IDL.Text),
  'explanation' : IDL.Text,
  'emotionalScore' : IDL.Nat,
  'credibilityScore' : IDL.Nat,
  'eli15' : IDL.Text,
  'confidence' : IDL.Nat,
  'classification' : AnalysisClassification,
});
export const VideoAnalysisResult = IDL.Record({
  'overallVerdict' : IDL.Text,
  'processingStatus' : IDL.Text,
  'suspiciousEdits' : IDL.Vec(IDL.Text),
  'confidence' : IDL.Nat,
  'editDetectionScore' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnalysisKind = IDL.Variant({
  'video' : IDL.Record({ 'videoBlob' : ExternalBlob }),
  'text' : IDL.Record({ 'snippet' : IDL.Text }),
  'image' : IDL.Record({ 'imageBlob' : ExternalBlob }),
});
export const Timestamp = IDL.Int;
export const HistoryItem = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'kind' : AnalysisKind,
  'credibilityScore' : IDL.Nat,
  'language' : IDL.Text,
  'summary' : IDL.Text,
  'timestamp' : Timestamp,
  'classification' : AnalysisClassification,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'analyzeImage' : IDL.Func([IDL.Text, IDL.Text], [ImageAnalysisResult], []),
  'analyzeText' : IDL.Func([IDL.Text, IDL.Text], [AnalysisResult], []),
  'analyzeVideo' : IDL.Func([IDL.Text, IDL.Text], [VideoAnalysisResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(HistoryItem)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ImageAnalysisResult = IDL.Record({
    'verdict' : IDL.Text,
    'authenticityScore' : IDL.Nat,
    'manipulationIndicators' : IDL.Vec(IDL.Text),
    'deepfakeScore' : IDL.Nat,
    'confidence' : IDL.Nat,
  });
  const AnalysisClassification = IDL.Variant({
    'misleading' : IDL.Null,
    'satire' : IDL.Null,
    'fake' : IDL.Null,
    'genuine' : IDL.Null,
  });
  const AnalysisResult = IDL.Record({
    'biasIndicator' : IDL.Text,
    'keyPhrases' : IDL.Vec(IDL.Text),
    'explanation' : IDL.Text,
    'emotionalScore' : IDL.Nat,
    'credibilityScore' : IDL.Nat,
    'eli15' : IDL.Text,
    'confidence' : IDL.Nat,
    'classification' : AnalysisClassification,
  });
  const VideoAnalysisResult = IDL.Record({
    'overallVerdict' : IDL.Text,
    'processingStatus' : IDL.Text,
    'suspiciousEdits' : IDL.Vec(IDL.Text),
    'confidence' : IDL.Nat,
    'editDetectionScore' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnalysisKind = IDL.Variant({
    'video' : IDL.Record({ 'videoBlob' : ExternalBlob }),
    'text' : IDL.Record({ 'snippet' : IDL.Text }),
    'image' : IDL.Record({ 'imageBlob' : ExternalBlob }),
  });
  const Timestamp = IDL.Int;
  const HistoryItem = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'kind' : AnalysisKind,
    'credibilityScore' : IDL.Nat,
    'language' : IDL.Text,
    'summary' : IDL.Text,
    'timestamp' : Timestamp,
    'classification' : AnalysisClassification,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'analyzeImage' : IDL.Func([IDL.Text, IDL.Text], [ImageAnalysisResult], []),
    'analyzeText' : IDL.Func([IDL.Text, IDL.Text], [AnalysisResult], []),
    'analyzeVideo' : IDL.Func([IDL.Text, IDL.Text], [VideoAnalysisResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(HistoryItem)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };