/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisClassification = { 'misleading' : null } |
  { 'satire' : null } |
  { 'fake' : null } |
  { 'genuine' : null };
export type AnalysisKind = { 'video' : { 'videoBlob' : ExternalBlob } } |
  { 'text' : { 'snippet' : string } } |
  { 'image' : { 'imageBlob' : ExternalBlob } };
export interface AnalysisResult {
  'biasIndicator' : string,
  'keyPhrases' : Array<string>,
  'explanation' : string,
  'emotionalScore' : bigint,
  'credibilityScore' : bigint,
  'eli15' : string,
  'confidence' : bigint,
  'classification' : AnalysisClassification,
}
export type ExternalBlob = Uint8Array;
export interface HistoryItem {
  'id' : bigint,
  'userId' : UserId,
  'kind' : AnalysisKind,
  'credibilityScore' : bigint,
  'language' : string,
  'summary' : string,
  'timestamp' : Timestamp,
  'classification' : AnalysisClassification,
}
export interface ImageAnalysisResult {
  'verdict' : string,
  'authenticityScore' : bigint,
  'manipulationIndicators' : Array<string>,
  'deepfakeScore' : bigint,
  'confidence' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoAnalysisResult {
  'overallVerdict' : string,
  'processingStatus' : string,
  'suspiciousEdits' : Array<string>,
  'confidence' : bigint,
  'editDetectionScore' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'analyzeImage' : ActorMethod<[string, string], ImageAnalysisResult>,
  'analyzeText' : ActorMethod<[string, string], AnalysisResult>,
  'analyzeVideo' : ActorMethod<[string, string], VideoAnalysisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAnalysisHistory' : ActorMethod<[], Array<HistoryItem>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];